version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12

  pre_build:
    commands:
      - echo Installing dependencies
      - npm install

  build:
    commands:
      - echo Running tests
      - npm test
      - echo Building and tagging Docker image
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 024147066791.dkr.ecr.us-east-2.amazonaws.com
      - docker build -t dockernode .
      - docker tag dockernode:latest 024147066791.dkr.ecr.us-east-2.amazonaws.com/dockernode:latest
      
  post_build:
    commands:
      - echo Pushing to ECR
      - docker push 024147066791.dkr.ecr.us-east-2.amazonaws.com/dockernode:latest
      - printf '[{"name":"dockernode","imageUri":"024147066791.dkr.ecr.us-east-2.amazonaws.com/dockernode:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
